apiVersion: v1
kind: Service
metadata:
  name: bind
  labels:
    name: bind
spec:
  type: LoadBalancer
  externalIPs:
  - 172.22.132.16
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
  selector:
    name: bind

